SECRET_MESSAGE_SENDER/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('SMS_APP.urls')),
]

SMS_APP/urls.py
from django.contrib import admin
from django.urls import path
from SMS_APP import views

app_name = "sms"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
]

SMS_APP/models.py
from django.db import models

# Create your models here.

SMS_APP/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'public/index.html')

templates/include/header.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>Document</title>
  </head>
  <body>
    <nav class="main-nav">
      <ul class="nav-list">
        <li class="nav-items">
          <a class="nav-item" href="{% url 'sms:index' %}">SecretMS</a>
        </li>
        <li class="nav-items">
          <a class="nav-item" href="{% url 'sms:index' %}">Home</a>
        </li>
        <li class="nav-items">
          <a class="nav-item" href="{% url 'sms:index' %}">About Us!</a>
        </li>

        <li class="nav-items">
          <a class="nav-item" href="{% url 'sms:index' %}">Login</a>
        </li>
      </ul>
    </nav>
    {% block nav_block %} {% endblock %} {% block body_block %} {% endblock %}
  </body>
</html>